### ISSUE TITLE
Cannot unselect Hypnotise/Rapid

### ISSUE THREAD

**Issue by maheshkkolla** [GautamSidtharth/tangles#2]
Once I click on Hypnotise then I am not able to unselect that. 
I tried to generate a Tangle after I clicked on Hypnotise. Tangle has generated But within a few seconds, it is automatically going back to Hypnotise mode. (Vice vera for Rapid mode as well)

**Comment by GautamSidtharth** [comment]
For now you can reload the page as solution. But this needs to be fixed. I will look into it.

**Comment by GautamSidtharth** [comment]
Issue `fixed`.
